---
# defaults file for libvirt-vm

lvvm_cloud_image: "{{ undef(hint='You must define the cloud image to base the VM on') }}"
lvvm_hostname: "{{ undef(hint='You must define the hostname of the VM') }}"
lvvm_domain: "{{ undef(hint='You must define a DNS domain for the VM') }}"
lvvm_default_pass: "{{ lookup('ansible.builtin.password', '/dev/null') }}"
lvvm_ssh_pwauth: false
lvvm_ssh_keys: "{{ undef(hint='You must define the user SSH keys for the VM') }}"

lvvm_ip_cidr: "{{ undef(hint='You must define the IP-CIDR for the VM') }}"
lvvm_ip_gateway: "{{ undef(hint='You must define the gateway for the VM') }}"
lvvm_nameservers: "{{ undef(hint='You must define the name servers for the VM') }}"

lvvm_vm_memory: 4096
lvvm_vm_cores: 4
lvvm_vm_os_disk_size: 50
lvvm_extra_config: ''
