---
# defaults file for libvirt-img

lv_libvirt_dir: "/var/lib/libvirt"

# Details of where to get the cloud image from
lv_cloud_image: "{{ undef(hint='You must define the cloud image to clone') }}"
lv_cloud_image_url: "{{ undef(hint='You must define the cloud image URL to clone') }}"
