---
all:
  hosts:
    localhost:
  vars:
    ansible_become_pass: "{{ lookup('ansible.builtin.env', 'BECOME_PASS') }}"
    ansible_connection: local

    # What IP address do you want to use (MUST already be on one of your interfaces)
    BOB_LISTEN_ADDRESS: '172.16.0.10'
    BOB_GATEWAY_ADDRESS: '172.16.0.254'
    BOB_DNS_SERVER: '172.16.0.254'

    # Local DNS Domain
    BOB_DNS_DOMAIN: 'home.lab'
    # Where to share the TFTP files from
    BOB_TFTP_DIRECTORY: '/var/lib/tftp'
    # Builder SSH key (to be put onto deployed images)
    BUILDER_SSH_KEY_FILE: '~/.ssh/id_rsa.pub'
    BUILDER_SSH_KEY: "{{ lookup('ansible.builtin.file', ''+BUILDER_SSH_KEY_FILE) }}"

    # Mirrors
    BOB_ALPINE_BASE_URL: 'https://uk.alpinelinux.org/alpine/v3.20'

    # Cloud Images
    ALPINE_QCOW_URL0: 'https://dl-cdn.alpinelinux.org/alpine/v3.20/releases/cloud/generic_alpine-3.20.3-x86_64-uefi-cloudinit-metal-r0.qcow2'
    ALPINE_QCOW_URL: 'http://sponge/cloud/generic_alpine-3.20.3-x86_64-uefi-cloudinit-metal-r0.qcow2'
    ALPINE_IMAGE_FILE: 'alpine-generic-3.20.3'
    ROCKY_QCOW_URL0: 'https://dl.rockylinux.org/pub/rocky/9/images/x86_64/Rocky-9-GenericCloud-Base-9.4-20240609.1.x86_64.qcow2'
    ROCKY_QCOW_URL: 'http://sponge/cloud/Rocky-9-GenericCloud-Base-9.4-20240609.1.x86_64.qcow2'
    ROCKY_IMAGE_FILE: 'Rocky-9.4-Generic-Base-20240609'
    UBUNTU_QCOW_URL0: 'https://cloud-images.ubuntu.com/oracular/20240927/oracular-server-cloudimg-amd64.img'
    UBUNTU_QCOW_URL: 'http://sponge/cloud/oracular-server-cloudimg-amd64.img'
    UBUNTU_IMAGE_FILE: 'Ubuntu-22.10-server-20240927'

    #-----------------------------------------------------------------------------------------------------------------------
    # DO NOT CHANGE BELOW HERE, unless you know what you are doing
    BOB_DNSMASQ_DIRECTORY: '/etc/dnsmasq.d'
    BOB_ETC_DIRECTORY: '/etc/bob'
    BOB_HTML_DIRECTORY: '/usr/share/nginx/html'
    # Bob's home
    BOB_HOME_DIRECTORY: '/opt/bob'
