---
all:
  hosts:
    localhost:
  vars:
    ansible_become_pass: "{{ lookup('ansible.builtin.env', 'BECOME_PASS') }}"
    ansible_connection: local

    ALPINE_SITE: 'https://uk.alpinelinux.org/alpine'

    # What IP address do you want to use (MUST already be on one of your interfaces)
    BOB_LISTEN_ADDRESS: '172.16.0.10'
    BOB_DHCP_GATEWAY: '172.16.0.254'
    BOB_DHCP_NAMESERVER: '172.16.0.254'
    # Local DNS Domain
    BOB_DNS_DOMAIN: 'home.lab'
    # Where to share the TFTP files from
    BOB_TFTP_DIRECTORY: '/var/lib/tftp'

    # Builder SSH key (to be put onto deployed images)
    BUILDER_SSH_KEY_FILE: '~/.ssh/id_rsa.pub'
    BUILDER_SSH_KEY: "{{ lookup('ansible.builtin.file', ''+BUILDER_SSH_KEY_FILE) }}"

    BOB_LOCAL_CACHE: 'http://sponge/cache'

    #-----------------------------------------------------------------------------------------------------------------------
    # DO NOT CHANGE BELOW HERE, unless you know what you are doing
    BOB_DNSMASQ_DIRECTORY: '/etc/dnsmasq.d'
    BOB_ETC_DIRECTORY: '/etc/bob'
    BOB_HTML_DIRECTORY: '/usr/share/nginx/html'
    # Bob's home
    BOB_HOME_DIRECTORY: '/opt/bob'
    BOB_RESCUE_VERSION: 'v3.20'
